const genres = [
    "ALL",
    "American",
    "Asian",
    "Bakery",
    "Belgian",
    "Bistro",
    "Cafe",
    "Coffee",
    "Contemporary",
    "Continental",
    "Eclectic",
    "European",
    "French",
    "Fusion",
    "Grill",
    "Hawaiian",
    "International",
    "Irish",
    "Italian",
    "Kosher",
    "Japanese",
    "Oysters",
    "Pacific Rim",
    "Pasta",
    "Polynesian",
    "Sandwiches",
    "Seafood",
    "Steak",
    "Sushi",
    "Tea",
    "Traditional",
    "Vegetarian",
    ""
]

export default genres;